version: "3.8"
services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "./entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3036:3036"
    depends_on:
      - db
      - redis
      - rabbitmq

volumes:
  db-data:
