FROM ruby:3.2.2 AS base

RUN apt-get update -qq && apt-get install -y \
  curl \
  gnupg \
  build-essential \
  libpq-dev \
  postgresql-client

# Node.js 18 + Yarn v1
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
  && apt-get install -y nodejs \
  && corepack enable && corepack prepare yarn@1.22.21 --activate

WORKDIR /app

FROM base AS development
ENV RAILS_ENV=development

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

CMD ["bash", "./entrypoint.sh"]
